<?php

try {

  $offer = Offer::getInstance((int) $req->id);

  $offer->deliver();

  $res->sendMessage(c(l('le message a bien Ã©tÃ© envoyÃ© aux destinataires de tests')));

}
catch (Exception $e) { $err->add($e); }